### ISSUE TITLE
How to add field webp to payloadcms field config

### ISSUE THREAD

**Issue by DanielKraemer** [chladog/payload-webp#12]
Hey together,

I want to add webp-support to my payloadcms project.

The readme.md includes the following sentence:
![grafik](https://user-images.githubusercontent.com/49027330/230776942-4291079d-261b-4222-a787-9ce67eaf1220.png)

But how should this field config look?

Currenctly I got the following error:
![grafik](https://user-images.githubusercontent.com/49027330/230776926-22cfaabf-e955-48df-92a1-212495eddb6e.png)

**Comment by chladog** [comment]
This should be fixed by fix of #11.
The config can be default as the required fields are added by plugin automatically.
