### ISSUE TITLE
Add Related GitHub Topics

### ISSUE THREAD

**Issue by denolfe** [chladog/payload-webp#2]
Hey chladog, the Payload team is trying to aggregate all of the plugins for payload on this page here: https://github.com/topics/payload-plugin

It would be great if you could add a few topics to your repo to make it show up there: `payload-plugin`, `payload`, and `payloadcms`. This is done by clicking the gear icon on the right side of your repo's main page. Thanks! 👍

**Comment by chladog** [comment]
hi @denolfe,
I have added the topics 👍
