### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by Etheliene** [chladog/payload-webp#7]
So far I have figured out that the plugin makes the following assumptions to my codebase:

1. The "uploads" collection needs `staticDir` to be defined or generation will fail
```
error - unhandledRejection: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at payload-webp\lib\WebpCollection.js:113:45
```  
2. `payload.config.ts|js` needs at least `[admin.](webpack: (config) => config,)` if you don't need a custom config or build will fail, as described in #6

```
TypeError: Cannot read properties of undefined (reading 'webpack')
\payload-webp\lib\Plugin.js:273
var incomingWebpackConfig = this.payloadConfig.admin.webpack;
```

Please update documentation

**Comment by chladog** [comment]
Hi Etheliene,
1. staticDir* is required at any payload upload collection, as stated here: https://payloadcms.com/docs/upload/overview ; thus I believe it should be handled by this plugin.
2. Fixed by f63279bdfe0f83d8f5a23a146f3b4ba78f669754
