### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by christian-reichart** [chladog/payload-webp#8]
Hello, great tool!
I wanted to try it but on install I get a lot of deprecation warnings, I think this has mainly to do with the Payload Version.

As I don't really know what to test for it's hard for me to create a PR and ensure that everything is still working as expected.

Thanks & Cheers

Update: I think the missing peer dependencies is a general problem of Payload. But npm tells me that since Version 1.0.1 this module depends on a vulnerable version of sharp.

With that, it would be maybe a good idea to update the dependency on Payload to some version >1.

**Comment by chladog** [comment]
hello @christian-reichart you are right, the versions are sometimes behind. Originally I tried to use newer version that Payload used, but that was failing (I guess it's not possible to combine multiple version of sharp binaries in single project). The versions  has been updated in payload and here as well to latest now.

When in need for future reference you can try to override the dependency version through [```resolutions``` field in package.json](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
